name: Metrics License
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Licenses and permissions
        with:
            filename: metrics.plugin.licenses.svg
            token: ${{ secrets.METRICS_TOKEN }}
            base: ""
            template: repository
            repo: metrics
            plugin_licenses: yes
            plugin_licenses_setup: npm ci
